language: php
sudo: false
cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/symfony-bridge/.phpunit
warnings_are_errors: false
services:
    - mysql
php:
    - 7.2

# Update composer
before-install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
    - composer self-update
  
install:
    - composer install --prefer-dist --no-interaction
    - php bin/console doctrine:database:create --env=travis
    - php bin/console doctrine:schema:create --env=travis
    - php bin/console doctrine:fixtures:load -n --env=travis
script:
    - ./vendor/bin/simple-phpunit --coverage-text --colors