monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped
            excluded_http_codes: [404, 405]
        #    type: fingers_crossed
        #    action_level: error
        #    handler: nested
        #    excluded_http_codes: [404, 405]
        #    buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        #nested:
        #    type: stream
        #    path: "%kernel.logs_dir%/%kernel.environment%.log"
        #    level: debug

        #console:
        #    type: console
        #    process_psr_3_messages: false
        #    channels: ["!event", "!doctrine"]
        grouped:    
            type:    group
            members: [streamed, deduplicated]
        streamed:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        deduplicated:
            type:    deduplication
            handler: swift
        swift:
            type:         swift_mailer
            from_email:   'dev.throuss@debug.com'
            to_email:     'debugapplogger@gmail.com'
            subject:      'An Error Occurred! %%message%%'
            level:        debug
            formatter:    monolog.formatter.html
            content_type: text/html
