index:
  path: /
  controller: App\Controller\RegistrationController::index
  methods: GET

image_routes:
  resource: './routes/ImageRouter'
  type:     directory

user_routes:
  resource: './routes/UserRouter'
  type:     directory

api_routes:
  resource: './routes/ApiRouter'
  type:     directory
