register:
  path: /register
  controller: App\Controller\RegistrationController::register
  methods: POST

login:
  path: /login
  controller: App\Controller\RegistrationController::login
  methods: POST

logout:
  path: /logout
  controller: App\Controller\RegistrationController::logout
  methods: GET