register:
  path: /register
  controller: App\Controller\RegistrationController::register
  methods: POST

login:
  path: /login
  controller: App\Controller\UserController::login
  methods: POST

logout:
  path: /logout
  methods: GET