register:
  path: /api/register
  controller: App\Controller\RegistrationController::register
  methods: POST

login:
  path: /api/login
  controller: App\Controller\RegistrationController::login
  methods: POST

logout:
  path: /api/logout
  controller: App\Controller\RegistrationController::logout
  methods: GET

profil:
  path: /api/profil
  controller: App\Controller\RegistrationController::profil
  methods: POST

admin:
  path: /api/admin/me
  controller: App\Controller\AdminController::me
  methods: POST

admin_fetch_user:
  path: /api/admin/users/fetch
  controller: App\Controller\AdminController::getUsers
  methods: GET

admin_delete_user:
  path: /api/admin/users/delete
  controller: App\Controller\AdminController::removeUser
  methods: DELETE